version: '3'

volumes:
  pgdata:
    external: false

services:
  backup:
    env_file:
      - .backup.env
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    command: tail -f /dev/null

  postgres:
    env_file:
      - .postgres.env
    image: postgres:12-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
